# config.py
from utils import resource_path
import os

config_path = 'settings.ini'

current_enemy_index = 0

enemy = None

enemy_offset_x = 20
#enemy_offset_y = 95
enemy_offset_y = 20

activate_HongLu_dodge = False
already_activate_HongLu_dodge = False
already_use_ego = False
#already_seen_battling = False
first_select = True
now_hit_refracted_generator = None
last_hit_refracted_generator = None
low_hp_ego = False
clash_disvantage_ego = True

stage_characters = ['李箱', '浮士德', '堂吉诃德', '良秀', '默尔索', '鸿璐', '希斯克里夫', '以实玛丽', '罗佳', '辛克莱', '奥提斯', '格里高尔']
characters_positions = {
    "李箱": (375, 330),
    "浮士德": (540, 330),
    "堂吉诃德": (700, 330),
    "良秀": (875, 330),
    "默尔索": (1040, 330),
    "鸿璐": (1200, 330),
    "希斯克里夫": (375, 570),
    "以实玛丽": (540, 570),
    "罗佳": (700, 570),
    "辛克莱": (875, 570),
    "奥提斯": (1040, 570),
    "格里高尔": (1200, 570),
}
enemy_options = [
    "第一站", "第二站", "第三站", "第四站"
]

enemy_names = [
    "第一站", "第一点二站", "第一点三站", "第一点四站", "第二站", "第二点二站", "第二点三站",
    "第二点四站", "第三站", "第三点二站", "第三点三站", "第四站", "第四点二站"
]

enemy_image_paths = {
    "第一站": resource_path("img/enemies/Section1.1"),
    "第一点二站": resource_path("img/enemies/Section1.2"),
    "第一点三站": resource_path("img/enemies/Section1.3"),
    "第一点四站": resource_path("img/enemies/CheckPoint"),
    "第二站": resource_path("img/enemies/Section2.1"),
    "第二点二站": resource_path("img/enemies/Section2.2"),
    "第二点三站": resource_path("img/enemies/Section2.3"),
    "第二点四站": resource_path("img/enemies/CheckPoint"),
    "第三站": resource_path("img/enemies/Section3.1"),
    "第三点二站": resource_path("img/enemies/Section3.2"),
    "第三点三站": resource_path("img/enemies/CheckPoint"),
    "第四站": resource_path("img/enemies/Section4.1"),
    "第四点二站": resource_path("img/enemies/Section4.2"),
}

internal_enemy_names = {
    "第一站": "Section1.1",
    "第一点二站": "Section1.2",
    "第一点三站": "Section1.3",
    "第一点四站": "CheckPoint1",
    "第二站": "Section2.1",
    "第二点二站": "Section2.2",
    "第二点三站": "Section2.3",
    "第二点四站": "CheckPoint2",
    "第三站": "Section3.1",
    "第三点二站": "Section3.2",
    "第三点三站": "CheckPoint3",
    "第四站": "Section4.1",
    "第四点二站": "Section4.2",
}


# 定义收益函数的超参数
reward_params = {
    "Dominating": 2.0,
    "Favored": 1.5,
    "Neutral": 1.0,
    "Unopposed": 0.9,
    "Struggling": 0.5,
    "Hopeless": 0.01,
    "Defense": 0.9,
    "OneSidedGuard": 0.01,
}

# 假设技能和敌人类型的初始收益参数，这里只是示例，具体需要根据实际情况定义
skill_enemy_params = {
    ("Unknown_s1", "ego"): 11.0,
    ("Sinclair_s1", "stagger"): 7.0,
    ("Sinclair_s1", "ego"): 1.4,
    ("Sinclair_s2", "stagger"): 20.0,
    ("Sinclair_s2", "ego"): 1.45,
    ("Sinclair_s2", "mirror_defend"): 2.5,
    ("Sinclair_s2", "minion_stagger"): 1.3,
    ("Sinclair_s2", "leave_interloper"): 1.2,
    #("Sinclair_s2", "thou_wilt_sink"): 1.4,
    #("Sinclair_s2", "chainbreaker"): 1.5,
    ("Sinclair_s3", "stagger"): 10.0,
    ("Sinclair_s3", "ego"): 1.5,
    ("Sinclair_s3", "minion_stagger"): 1.2,
    ("Sinclair_s3", "leave_interloper"): 1.3,
    ("Sinclair_s3", "purple_electric_screaming"): 1.5,
    #("Sinclair_s3", "thou_wilt_sink"): 1.3,
    #("Sinclair_s3", "chainbreaker"): 1.45,
    ("Sinclair_branch", "purple_electric_screaming"): 2.8,
    ("Sinclair_dodge", "dodge"): 5.0,
    ("HongLu_s1", "stagger"): 15.0,
    ("HongLu_s1", "ego"): 1.45,
    ("HongLu_s1", "mirror_defend"): 2.5,
    ("HongLu_s1", "minion_stagger"): 1.2,
    ("HongLu_s2", "stagger"): 20.0,
    ("HongLu_s2", "ego"): 1.5,
    ("HongLu_s2", "mirror_defend"): 3.0,
    ("HongLu_s2", "minion_stagger"): 1.3,
    #("HongLu_s2", "thou_wilt_sink"): 1.4,
    #("HongLu_s2", "chainbreaker"): 1.5,
    ("HongLu_s3", "stagger"): 10.0,
    ("HongLu_s3", "ego"): 1.4,
    ("HongLu_s3", "constricted_stagger"): 1.6,
    ("HongLu_s3", "mirror_defend"): 2.4,
    ("HongLu_s3", "minion_stagger"): 0.19,
    #("HongLu_s3", "thou_wilt_sink"): 0.13,
    #("HongLu_s3", "chainbreaker"): 0.135,
    ("HongLu_land", "draining_roots"): 0.5,
    ("HongLu_land", "it_shall_shun"): 2.1,
    ("YiSang_s1", "stagger"): 7.0,
    ("YiSang_s1", "ego"): 1.4,
    ("YiSang_s2", "stagger"): 10.0,
    ("YiSang_s2", "ego"): 1.45,
    ("YiSang_s2", "minion_stagger"): 1.3,
    ("YiSang_s3", "stagger"): 20.0,
    ("YiSang_s3", "ego"): 1.5,
    ("YiSang_s3", "mirror_defend"): 2.5,
    ("YiSang_s3", "minion_stagger"): 1.2,
    ("YiSang_sunshower", "purple_electric_screaming"): 2.8,
    ("LamentYiSang_s1", "stagger"): 7.0,
    ("LamentYiSang_s1", "ego"): 1.4,
    ("LamentYiSang_s2", "stagger"): 10.0,
    ("LamentYiSang_s2", "ego"): 1.45,
    ("LamentYiSang_s2", "minion_stagger"): 1.2,
    ("LamentYiSang_s3", "stagger"): 20.0,
    ("LamentYiSang_s3", "ego"): 1.5,
    ("LamentYiSang_s3", "mirror_defend"): 2.5,
    ("LamentYiSang_s3", "minion_stagger"): 1.3,
    ("LamentYiSang_sunshower", "purple_electric_screaming"): 2.8,
    ("Heathcliff_s1", "stagger"): 7.0,
    ("Heathcliff_s1", "ego"): 1.4,
    ("Heathcliff_s2", "stagger"): 10.0,
    ("Heathcliff_s2", "ego"): 1.45,
    ("Heathcliff_s2", "mirror_defend"): 2.5,
    ("Heathcliff_s2", "minion_stagger"): 1.3,
    ("Heathcliff_s3", "stagger"): 20.0,
    ("Heathcliff_s3", "ego"): 1.5,
    ("Heathcliff_s3", "minion_stagger"): 1.2,
    #("Heathcliff_s3", "chainbreaker"): 1.4,
    #("Heathcliff_s3", "thou_wilt_sink"): 1.3,
    ("Heathcliff_binds", "purple_electric_screaming"): 2.8,
    ("WildHuntHeathcliff_s1", "stagger"): 7.0,
    ("WildHuntHeathcliff_s1", "ego"): 1.4,
    ("WildHuntHeathcliff_s2", "stagger"): 10.0,
    ("WildHuntHeathcliff_s2", "ego"): 1.45,
    ("WildHuntHeathcliff_s2", "mirror_defend"): 2.5,
    ("WildHuntHeathcliff_s2", "minion_stagger"): 1.3,
    ("WildHuntHeathcliff_s3", "stagger"): 20.0,
    ("WildHuntHeathcliff_s3", "ego"): 1.5,
    ("WildHuntHeathcliff_s3", "minion_stagger"): 1.2,
    ("WildHuntHeathcliff_s4", "stagger"): 20.0,
    ("WildHuntHeathcliff_s4", "ego"): 1.5,
    ("WildHuntHeathcliff_s4", "minion_stagger"): 1.2,
    ("WildHuntHeathcliff_binds", "purple_electric_screaming"): 2.8,
    ("Ismael_s1", "stagger"): 7.0,
    ("Ismael_s1", "ego"): 1.4,
    ("Ismael_s2", "stagger"): 10.0,
    ("Ismael_s2", "ego"): 1.45,
    ("Ismael_s2", "mirror_defend"): 2.5,
    ("Ismael_s2", "minion_stagger"): 1.3,
    ("Ismael_s3", "stagger"): 20.0,
    ("Ismael_s3", "ego"): 1.5,
    ("Ismael_s3", "minion_stagger"): 1.2,
    ("Ismael_blind", "purple_electric_screaming"): 2.8,
    ("RyoShu_s1", "stagger"): 7.0,
    ("RyoShu_s1", "ego"): 1.4,
    ("RyoShu_s2", "stagger"): 10.0,
    ("RyoShu_s2", "ego"): 1.45,
    ("RyoShu_s2", "mirror_defend"): 2.5,
    ("RyoShu_s2", "minion_stagger"): 1.3,
    ("RyoShu_s2", "coerced_jugment"): 1.3,
    ("RyoShu_s2", "amoral_enactment"): 1.3,
    #("RyoShu_s2", "thou_wilt_sink"): 1.4,
    #("RyoShu_s2", "chainbreaker"): 1.5,
    ("RyoShu_s3", "stagger"): 20.0,
    ("RyoShu_s3", "ego"): 1.5,
    ("RyoShu_s3", "minion_stagger"): 1.2,
    ("RyoShu_s3", "sky_clearing_cut"): 1.5,
    ("RyoShu_s3", "purple_electric_screaming"): 1.5,
    ("RAPRyoShu_s1", "stagger"): 7.0,
    ("RAPRyoShu_s1", "ego"): 1.4,
    ("RAPRyoShu_s2", "stagger"): 10.0,
    ("RAPRyoShu_s2", "ego"): 1.45,
    ("RAPRyoShu_s2", "mirror_defend"): 2.5,
    ("RAPRyoShu_s2", "minion_stagger"): 1.3,
    #("RyoShu_s2", "thou_wilt_sink"): 1.4,
    #("RyoShu_s2", "chainbreaker"): 1.5,
    ("RAPRyoShu_s3", "stagger"): 20.0,
    ("RAPRyoShu_s3", "ego"): 1.5,
    ("RAPRyoShu_s3", "minion_stagger"): 1.2,
    ("RAPRyoShu_s3", "sky_clearing_cut"): 1.5,
    #("RyoShu_s3", "thou_wilt_sink"): 1.3,
    #("RyoShu_s3", "chainbreaker"): 1.45,
    ("RAPRyoShu_defend", "dodge"): 5.0,
    ("DonQuixote_s1", "stagger"): 7.0,
    ("DonQuixote_s1", "ego"): 1.4,
    ("DonQuixote_s2", "stagger"): 10.0,
    ("DonQuixote_s2", "ego"): 1.45,
    ("DonQuixote_s2", "mirror_defend"): 2.5,
    ("DonQuixote_s2", "minion_stagger"): 1.3,
    ("DonQuixote_s3", "stagger"): 20.0,
    ("DonQuixote_s3", "ego"): 1.5,
    ("DonQuixote_s3", "sky_clearing_cut"): 1.5,
    ("DonQuixote_s3", "purple_electric_screaming"): 1.5,
    #("DonQuixote_s3", "thou_wilt_sink"): 1.3,
    #("DonQuixote_s3", "chainbreaker"): 1.4,
    ("DonQuixote_dodge", "dodge"): 5.0,
    ("Rodion_s1", "stagger"): 7.0,
    ("Rodion_s1", "ego"): 1.4,
    ("Rodion_s2", "stagger"): 10.0,
    ("Rodion_s2", "ego"): 1.45,
    ("Rodion_s2", "mirror_defend"): 2.1,
    ("Rodion_s2", "minion_stagger"): 1.2,
    ("Rodion_s3", "stagger"): 20.0,
    ("Rodion_s3", "ego"): 1.5,
    ("Rodion_s3", "mirror_defend"): 2.5,
    ("Rodion_s3", "minion_stagger"): 1.3,
    ("Rodion_s3", "minion_stagger"): 1.3,
    ("Rodion_what", "leave_interloper"): 3.0,
    ("Rodion_what", "amoral_enactment"): 5.0,
    ("Rodion_what", "sky_clearing_cut"): 2.5,
    ("Rodion_what", "purple_electric_screaming"): 2.8,
    ("Rodion_defend", "dodge"): 5.0,
    ("Outis_s1", "stagger"): 7.0,
    ("Outis_s1", "ego"): 1.4,
    ("Outis_s2", "stagger"): 10.0,
    ("Outis_s2", "ego"): 1.45,
    ("Outis_s2", "mirror_defend"): 2.1,
    ("Outis_s2", "minion_stagger"): 1.2,
    ("Outis_s3", "stagger"): 20.0,
    ("Outis_s3", "ego"): 1.5,
    ("Outis_s3", "mirror_defend"): 2.5,
    ("Outis_s3", "minion_stagger"): 1.3,
    #("Outis_s3", "chainbreaker"): 1.4,
    ("Outis_ebony", "purple_electric_screaming"): 2.8,
    ("Outis_binds", "purple_electric_screaming"): 2.8,
    ("Outis_defend", "dodge"): 5.0,
    ("Faust_s1", "stagger"): 7.0,
    ("Faust_s1", "ego"): 1.4,
    ("Faust_s2", "stagger"): 10.0,
    ("Faust_s2", "ego"): 1.45,
    ("Faust_s2", "mirror_defend"): 2.5,
    ("Faust_s2", "minion_stagger"): 1.3,
    ("Faust_s3", "stagger"): 20.0,
    ("Faust_s3", "ego"): 1.5,
    ("Faust_s3", "minion_stagger"): 1.2,
    #("Faust_fluid", "thou_wilt_sink"): 2.8,
    #("Faust_fluid", "chainbreaker"): 2.9,
    ("Faust_defend", "dodge"): 5.0,
    ("SevenFaust_s1", "stagger"): 7.0,
    ("SevenFaust_s1", "ego"): 1.4,
    ("SevenFaust_s2", "stagger"): 10.0,
    ("SevenFaust_s2", "ego"): 1.45,
    ("SevenFaust_s2", "mirror_defend"): 2.5,
    ("SevenFaust_s2", "minion_stagger"): 1.3,
    ("SevenFaust_s3", "stagger"): 20.0,
    ("SevenFaust_s3", "ego"): 1.5,
    ("SevenFaust_s3", "minion_stagger"): 1.2,
    #("SevenFaust_fluid", "thou_wilt_sink"): 2.8,
    #("SevenFaust_fluid", "chainbreaker"): 2.9,
    ("SevenFaust_defend", "dodge"): 5.0,
    ("CrackFaust_s1", "stagger"): 7.0,
    ("CrackFaust_s1", "ego"): 1.4,
    ("CrackFaust_s2", "stagger"): 10.0,
    ("CrackFaust_s2", "ego"): 1.45,
    ("CrackFaust_s2", "mirror_defend"): 2.5,
    ("CrackFaust_s2", "minion_stagger"): 1.3,
    ("CrackFaust_s3", "stagger"): 20.0,
    ("CrackFaust_s3", "ego"): 1.5,
    ("CrackFaust_s3", "minion_stagger"): 1.2,
    #("SevenFaust_fluid", "thou_wilt_sink"): 2.8,
    #("SevenFaust_fluid", "chainbreaker"): 2.9,
    ("CrackFaust_defend", "dodge"): 5.0,
}

default_low_reward = {
    "Unknown_s1":10,
    "Sinclair_s1": 1.0,
    "Sinclair_s2": 0.8,
    "Sinclair_s3": 0.76,
    "Sinclair_dodge": 0.01,
    "Sinclair_branch": 2.0,
    "Heathcliff_s1": 1.0,
    "Heathcliff_s2": 0.8,
    "Heathcliff_s3": 0.59,
    "Heathcliff_dodge": 0.01,
    "Heathcliff_bodysack": 2.0,
    "Heathcliff_binds": 2.0,
    "WildHuntHeathcliff_s1": 0.8,
    "WildHuntHeathcliff_s2": 0.7,
    "WildHuntHeathcliff_s3": 1.0,
    "WildHuntHeathcliff_s4": 1.0,
    "WildHuntHeathcliff_defend": 5.0,
    "WildHuntHeathcliff_bodysack": 2.0,
    "WildHuntHeathcliff_binds": 2.0,
    "Ismael_s1": 1.0,
    "Ismael_s2": 0.8,
    "Ismael_s3": 0.7,
    "Ismael_defend": 0.01,
    "Ismael_snagharpoon": 2.0,
    "Ismael_blind": 2.0,
    "YiSang_s1": 1.0,
    "YiSang_s2": 0.8,
    "YiSang_s3": 0.76,
    "YiSang_defend": 0.01,
    "YiSang_crow": 2.0,
    "YiSang_dimension": 2.0,
    "YiSang_sunshower": 2.0,
    "LamentYiSang_s1": 1.0,
    "LamentYiSang_s2": 0.8,
    "LamentYiSang_s3": 0.76,
    "LamentYiSang_defend": 0.01,
    "LamentYiSang_crow": 2.0,
    "LamentYiSang_dimension": 2.0,
    "LamentYiSang_sunshower": 2.0,
    "RyoShu_s1": 1.0,
    "RyoShu_s2": 0.8,
    "RyoShu_s3": 0.59,
    "RyoShu_dodge": 0.01,
    "RyoShu_forest": 1.5,
    "RAPRyoShu_s1": 1.0,
    "RAPRyoShu_s2": 0.8,
    "RAPRyoShu_s3": 0.7,
    "RAPRyoShu_defend": 0.01,
    "RAPRyoShu_forest": 1.5,
    "DonQuixote_s1": 1.0,
    "DonQuixote_s2": 0.8,
    "DonQuixote_s3": 0.59,
    "DonQuixote_dodge": 0.01,
    "DonQuixote_la": 2.0,
    "HongLu_s1": 0.8,
    "HongLu_s2": 1.0,
    "HongLu_s3": 0.09,
    "HongLu_land": 2.0,
    "HongLu_dodge": 0.01,
    "Rodion_s1": 0.76,
    "Rodion_s2": 0.8,
    "Rodion_s3": 1.0,
    "Rodion_defend": 0.01,
    "Rodion_what": 2.0,
    "Rodion_rime": 2.0,
    "Outis_s1": 0.76,
    "Outis_s2": 0.8,
    "Outis_s3": 1.0,
    "Outis_defend": 0.01,
    "Outis_to": 2.0,
    "Outis_ebony": 2.0,
    "Outis_binds": 2.0,
    "Faust_s1": 1.0,
    "Faust_s2": 0.8,
    "Faust_s3": 0.76,
    "Faust_defend": 0.01,
    "Faust_emitter": 2.0,
    "Faust_fluid": 2.0,
    "CrackFaust_s1": 1.0,
    "CrackFaust_s2": 0.8,
    "CrackFaust_s3": 0.76,
    "CrackFaust_defend": 0.01,
    "CrackFaust_emitter": 2.0,
    "CrackFaust_fluid": 2.0,
    "SevenFaust_s1": 1.0,
    "SevenFaust_s2": 0.8,
    "SevenFaust_s3": 0.76,
    "SevenFaust_defend": 0.01,
    "SevenFaust_emitter": 2.0,
    "SevenFaust_fluid": 2.0,
}


